version: '3.7'
services:
  fastapi:
    container_name: fastapi
    build: 
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8081:8000"
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
  wsapp:
    container_name: wsfastapi
    build: 
      context: .
      dockerfile: Dockerfile2
    ports:
      - "8082:8000"
    working_dir: /ws-app
    tty: true
    volumes:
      - ./ws-app:/ws-app
  redis:
    container_name: redis1
    image: redis:alpine
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8090:8081
  nodejs:
    container_name: nodejs
    build: 
      context: .
      dockerfile: Dockerfile3
    ports:
      - "8083:3000"
    tty: true
    volumes:
      - ./node-app:/node-app

  mainweb:
    container_name: nodejs
    build: 
      context: .
      dockerfile: Dockerfile4
    ports:
      - "8085:3000"
    tty: true
    volumes:
      - ./web:/web